"""Refresh config/universe_sp_ftse.json from live S&P 500 + FTSE 100
constituent tables (Wikipedia), reporting which tickers were added/removed
since the last build — e.g. index-provider drops (delisting, acquisition,
take-private) or additions.

full_scan.build_sp_ftse_universe() already does the fetch-and-write; this
just wraps it with a before/after diff so a periodic refresh (index
membership changes a few times a year) doesn't require running the full
multi-strategy sweep in full_scan_all_strategies.py just to pick it up.

Does NOT touch config/watchlist_*.json — those are the live daemon's actual
trading lists and are only regenerated by regen_watchlists.py, deliberately
run separately so the diff can be reviewed first.

Usage:
    uv run python -m Strategy_Auto_Trader.markov_cli.refresh_universe
"""

from __future__ import annotations

import json
import sys

from . import full_scan
from ..core.cli_logging import setup_cli_logger


def main() -> int:
    setup_cli_logger("refresh_universe")

    before = set()
    if full_scan.SP_FTSE_UNIVERSE_FILE.exists():
        before = set(json.loads(
            full_scan.SP_FTSE_UNIVERSE_FILE.read_text(encoding="utf-8"))["tickers"])

    after = set(full_scan.build_sp_ftse_universe())

    removed = sorted(before - after)
    added = sorted(after - before)
    print(f"\nUniverse: {len(before)} -> {len(after)} tickers")
    print(f"Removed ({len(removed)}): {removed}" if removed else "Removed: none")
    print(f"Added ({len(added)}): {added}" if added else "Added: none")
    if removed:
        print("\nRemoved tickers likely still sit in config/watchlist_*.json — "
              "run regen_watchlists.py and review its diff to sync those too.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
