Set-Location "C:\Users\Craig\.claude\skills\Strategy_Auto_Trader"
New-Item -ItemType Directory -Force -Path "logs" | Out-Null
$log = "logs\warm_sp_night2_$(Get-Date -Format yyyyMMdd_HHmmss).log"
uv run python -m Strategy_Auto_Trader.synthetic_backtest_data.warm_hmm_cache `
  --tickers A AAPL ABBV ABNB ABT ACGL ACN ADBE ADI ADM ADP ADSK AEE AEP AES AFL AIG AIZ AJG AKAM ALB ALGN ALL ALLE AMAT AMCR AMD AME AMGN AMP AMT AMZN ANET AON AOS APA APD APH APO APP APTV ARE ARES ATO AVGO AVY AWK AXON AXP AZO BA BAC BALL BAX BBY BDX BEN BF-B BG BIIB BKNG BKR BLDR BLK BMY BNY BR BRK-B BRO BSX BX BXP C CAH CARR CASY CAT CB CBOE CBRE CCI CCL CDNS CDW CEG CF CFG CHD CHRW CHTR CI CIEN CINF CL CLX CMCSA CME CMG CMI CMS CNC CNP COF COHR COIN COO COP COR COST CPAY CPRT CPT CRH CRL CRM CRWD CSCO CSGP CSX CTAS CTSH CTVA CVNA CVS CVX D DAL DASH DD DDOG DE DECK DELL DG DGX DHI DHR DIS DLR DLTR DOC DOV DOW DPZ DRI DTE DUK DVA DVN DXCM EBAY ECHO ECL ED EFX EG EIX EL ELV EME EMR EOG EQIX EQT ERIE ES ESS ETN ETR EVRG `
  --start-date 1999-09-01 `
  --end-date 2026-09-01 `
  --workers 2 2>&1 | Tee-Object -FilePath $log
exit $LASTEXITCODE
