Set-Location "C:\Users\Craig\.claude\skills\Strategy_Auto_Trader"
New-Item -ItemType Directory -Force -Path "logs" | Out-Null
$log = "logs\warm_sp_night3_$(Get-Date -Format yyyyMMdd_HHmmss).log"
uv run python -m Strategy_Auto_Trader.synthetic_backtest_data.warm_hmm_cache `
  --tickers EW EXC EXE EXPD EXPE EXR F FANG FAST FCX FDS FDX FDXF FE FERG FFIV FICO FIS FISV FITB FIX FLEX FOX FOXA FRT FSLR FTNT FTV GD GDDY GE GEHC GEN GEV GILD GIS GL GLW GM GNRC GOOG GOOGL GPC GPN GRMN GS GWW HAL HAS HBAN HCA HD HIG HII HLT HON HONA HOOD HPE HPQ HRL HSIC HST HSY HUBB HUM HWM IBKR IBM ICE IDXX IEX IFF INCY INTC INTU INVH IP IQV IR IRM ISRG IT ITW IVZ J JBHT JBL JCI JKHY JNJ JPM KDP KEY KEYS KHC KIM KKR KLAC KMB KMI KO KR KVUE L LDOS LEN LH LHX LII LIN LITE LLY LMT LNT LOW LRCX LULU LUV LVS LYB LYV MA MAA MAR MAS MCD MCHP MCK MCO MDLZ MDT MET META MGM MKC MLM MMM MNST MO MOS MPC MPWR MRK MRNA MRSH MRVL MS MSCI MSFT MSI MTB MTD MU NCLH NDAQ NDSN NEE NEM NFLX NI NKE NOC NOW NRG NSC NTAP NTRS NUE NVDA `
  --start-date 1999-09-01 `
  --end-date 2026-09-01 `
  --workers 2 2>&1 | Tee-Object -FilePath $log
exit $LASTEXITCODE
