Set-Location "C:\Users\Craig\.claude\skills\Strategy_Auto_Trader"
New-Item -ItemType Directory -Force -Path "logs" | Out-Null
$log = "logs\warm_sp_night4_$(Get-Date -Format yyyyMMdd_HHmmss).log"
uv run python -m Strategy_Auto_Trader.synthetic_backtest_data.warm_hmm_cache `
  --tickers NVR NWS NWSA NXPI O ODFL OKE OMC ON ORCL ORLY OTIS OXY PANW PAYX PCAR PCG PEG PEP PFE PFG PG PGR PH PHM PKG PLD PLTR PM PNC PNR PNW PODD PPG PPL PRU PSA PSKY PSX PTC PWR PYPL Q QCOM RCL RDDT REG REGN RF RJF RL RMD ROK ROL ROP ROST RSG RTX RVTY SBAC SBUX SCHW SHW SJM SLB SMCI SNA SNDK SNPS SO SOLV SPG SPGI SRE STE STLD STT STX STZ SW SWK SWKS SYF SYK SYY T TAP TDG TDY TECH TEL TER TFC TGT TJX TKO TMO TMUS TPL TPR TRGP TRMB TROW TRV TSCO TSLA TSN TT TTD TTWO TXN TXT TYL UAL UBER UDR UHS ULTA UNH UNP UPS URI USB V VEEV VICI VLO VLTO VMC VMRK VRSK VRSN VRT VRTX VST VTR VTRS VZ WAB WAT WBD WDAY WDC WEC WELL WFC WM WMB WMT WRB WSM WST WTW WY WYNN XEL XOM XYL XYZ YUM ZBH ZBRA ZTS `
  --start-date 1999-09-01 `
  --end-date 2026-09-01 `
  --workers 2 *>&1 | Tee-Object -FilePath $log
exit $LASTEXITCODE
