"""Protocol contract for broker adapters.

Any concrete adapter (IBKRAdapter, NullBroker, …) must satisfy
BrokerAdapterProtocol so it can be swapped in tests or extended later.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from .types import FillResult, OrderRequest, StopOrderRequest, StopOrderResult, OpenOrderInfo


@runtime_checkable
class BrokerAdapterProtocol(Protocol):
    """Minimal interface for placing and querying orders."""

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def get_last_price(self, ticker: str) -> float: ...
    def place_order(self, req: OrderRequest) -> FillResult | None: ...
    def get_open_positions(self) -> dict[str, int]: ...
    def get_open_orders(self) -> list[dict]: ...
    def place_stop_order(self, req: StopOrderRequest) -> StopOrderResult | None: ...
    def get_open_stop_orders(self) -> dict[int, OpenOrderInfo]: ...
    def cancel_stop_order(self, perm_id: int) -> str: ...
    def get_stop_fill(self, perm_id: int) -> FillResult | None: ...
